version: '3'

services:
  mydjango:
    build:
      ./mydjango/
    # links:
    #   - postgres:postgres
    #   - redis:redis
    # env_file:
    #   postgres-variables.env
    volumes:
      - ./mydjango:/data/web
    command:
      gunicorn mydjango.wsgi:application -w 2 -b :8000
    networks: 
      - nginx_network
  nginx:
    image:
      nginx:1.13
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - mydjango
    networks: 
      - nginx_network
networks: 
  nginx_network:
    driver:
      bridge
  # postgres:
  #   restart: 
  #     always
  #   image: 
  #     postgres:latest
  #   volumes:
  #     - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #     - ./backups/postgresql:/backup
  #   env_file:
  #     - postgres-variables.env
  #   expose:
  #     - "5432"
  # redis:
  #   image: 
  #     redis:latest
  #   expose:
  #     - "6379"
  # data:
  #   image: 
  #     alpine
  #   volumes:
  #     - /var/lib/postgresql
  #   command: 
  #     "true"
