version: '3'

services:
  mydjango:
    build:
      ./mydjango/
    # links:
    #   - postgres:postgres
    #   - redis:redis
    env_file:
      postgres-variables.env
    volumes:
      - ./mydjango:/data/web
      - static_volume:/data/web/mydjango/static/
      - media_volume:/data/web/mydjango/media/
    command:
      gunicorn mydjango.wsgi:application -w 2 -b :8000
    networks: 
      - nginx_network
      - db_pr_web_network
    depends_on:
      - db_pr_web
  nginx:
    image:
      nginx:1.13
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - static_volume:/data/web/mydjango/static/
      - media_volume:/data/web/mydjango/media/
    depends_on:
      - mydjango
    networks: 
      - nginx_network
  db_pr_web:
    image: 
      postgres:latest
    env_file:
      - postgres-variables.env
    networks:
      - db_pr_web_network
    volumes:
      - db_pr_web_volume:/var/lib/postgresql/data
      # - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  # redis:
  #   image: 
  #     redis:latest
  #   expose:
  #     - "6379"
  # data:
  #   image: 
  #     alpine
  #   volumes:
  #     - /var/lib/postgresql
  #   command: 
  #     "true"
networks: 
  nginx_network:
    driver:
      bridge
  db_pr_web_network:
    driver:
      bridge
volumes:
  db_pr_web_volume:
  static_volume:
  media_volume: